name : CustomerApi-CI
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - CustomerApi/*

pool:
  vmImage: 'ubuntu-latest'

variables:  
  AzureSubscription: 'AZC' # Name of the Service Connection
  ApiName: 'customerapi'
  ArtifactName: 'CustomerApi'
  BuildId: $(Build.BuildId)
  BuildNumber: $(GitVersion.NuGetVersionV2)
  ClusterResourceGroup: MicroserviceDemo  
  ChartPackage: '$(Build.ArtifactStagingDirectory)/$(ApiName)-$(BuildNumber).tgz'
  ChartPath: '$(ArtifactName)/$(ArtifactName)/charts/$(ApiName)'
  ConnectionString: "Server=tcp:$(SQLServerName),1433;Initial Catalog=$(DatabaseName);Persist Security Info=False;User ID=$(DbUser);Password=$(DbPassword);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
  DatabaseName: Customer
  HelmVersion: 3.5.0  
  Repository: 'wolfgangofner/$(ApiName)' # '<YourACRName>.azurecr.io/<YourRepositoryName>' # replace with your repository
  K8sNamespace: '$(ApiName)-test'
  KubernetesCluster: 'microservice-aks'
  ReleaseValuesFile: '$(ArtifactName)/$(ArtifactName)/values.release.yaml'
  SQLServerName: wolfgangmicroservicedemoserver.database.windows.net # replace with your server url

resources:
  containers:
  - container: nginx
    image: jollyroger911/ngx:153

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps: 
    - template: templates/BuildVersioning.yml
    - template: templates/DockerBuildAndPush.yml
      parameters:
          buildId: $(BuildId)
          patMicroserviceDemoNugetsFeed: $(PatMicroserviceDemoNugetsFeed)
          containerRegistry: 'DH' # MicroserviceDemoRegistry # replace with your Service Connection name
          repository: $(Repository) 
          tag: $(BuildNumber)
          artifactName: $(ArtifactName)
    - template: templates/HelmInstall.yml
      parameters: 
          helmVersion: $(HelmVersion)
          releaseValuesFile: $(ReleaseValuesFile)
    - template: templates/HelmDeploy.yml
      parameters:          
          apiName: $(ApiName)
          azureSubscription: $(AzureSubscription)
          buildNumber: $(BuildNumber)
          clusterResourceGroup: $(ClusterResourceGroup)
          chartPackage: $(ChartPackage)
          chartPath: $(ChartPath)
          k8sNamespace: $(K8sNamespace)
          kubernetesCluster: $(KubernetesCluster)        
          releaseValuesFile: $(ReleaseValuesFile)