variables:
  AzureSubscription: 'AZC' # Name of the Service Connection
  ApiName: 'ngx'
  ClusterResourceGroup: ks06group  
  ChartPackage: '$(Build.ArtifactStagingDirectory)/$(ApiName)-$(Build.BuildNumber).tgz'  
  ChartPath: 'CustomerApi/CustomerApi/charts/$(ApiName)'
  HelmVersion: 3.5.0
  ImageName: 'jollyroger911/$(ApiName):$(Build.BuildNumber)'
  K8sNamespace: '$(ApiName)-test'
  KubernetesCluster: 'ks06AKS'

tasks:
  - task: HelmInstaller@0
    inputs:
      helmVersion: '2.14.1'
      installKubectl: true

  - task: HelmDeploy@0
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscription: 'AZC'
      azureResourceGroup: 'ks06group'
      kubernetesCluster: 'ks06AKS'
      namespace: 'ks06'
      command: 'ls'