name : Docker-CI
trigger :
  branches:
    include:
      - master

pool: pool

variables:
  ImageName: 'jollyroger911/ngx:150'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
    - script: cp ~/ks07/nginx/privkey.pem ./
      displayName: 'Copy private key'    
    - script: cp ~/ks07/nginx/fullchain.pem ./
      displayName: 'Copy fullchain'          
    - script: cp ~/ks07/nginx/index.html ./
      displayName: 'Copy index.html'    
    - script: cp ~/ks07/nginx/kubernetes.png ./
      displayName: 'Copy kubernetes'          
    - script: cp ~/ks07/nginx/ilon.jpg ./
      displayName: 'Copy Ilon'    

    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DH'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(ImageName)'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: '.'
        
- stage: Push
  displayName: Push image
  jobs:  
  - job: DockerImage_Push
    displayName: Push Docker image
    steps:
    - task: Docker@1
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DH'
        command: 'Push an image'
        imageName: '$(ImageName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))


    - task: CmdLine@2
      inputs:
        script: |
          helmVersion=helm-v3.0.0-rc.3-linux-amd64.tar.gz
          
          wget https://get.helm.sh/$helmVersion
          tar xvzf $helmVersion
          sudo mv linux-amd64/helm /usr/bin/helm

    - task: HelmDeploy@0
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'AZC'
        azureResourceGroup: 'ks06group'
        kubernetesCluster: 'ks06AKS'
        namespace: 'ks06'
        command: 'ls'