name : Docker-CI
trigger :
  branches:
    include:
      - master

pool: myPool

variables:
  ImageName: 'ngx/ado:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
    - script: cp ~/dockefiles/nginxConfig/b02/privkey.pem ./
      displayName: 'Copy private key'    
    - script: cp ~/dockefiles/nginxConfig/b02/fullchain.pem ./
      displayName: 'Copy fullchain'          
    - script: cp ~/dockefiles/nginxConfig/b02/index.html ./
      displayName: 'Copy index.html'    
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DH'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(ImageName)'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: '.'
        
- stage: Push
  displayName: Push image
  jobs:  
  - job: DockerImage_Push
    displayName: Push Docker image
    steps:
    - task: Docker@1
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Container Registry'
        repository: 'nginx'
        dockerRegistryEndpoint: 'DH'
        command: 'Push an image'
        imageName: '$(ImageName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

