name : Docker-CI
trigger :
  branches:
    include:
      - master

pool: myPool

variables:
  ImageName: 'ngx/ado:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
    - script: cp ~/dockefiles/nginxConfig/b02/privkey.pem ./
      displayName: 'Copy private key'    
    - script: cp ~/dockefiles/nginxConfig/b02/fullchain.pem ./
      displayName: 'Copy fullchain'          
    - script: cp ~/dockefiles/nginxConfig/b02/index.html ./
      displayName: 'Copy index.html'    
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DH'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: 'ngx/ado'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: '.'
        
- stage: Push
  displayName: Push image
  jobs:  
  - job: DockerImage_Push
    displayName: Push Docker image
    steps:
    - task: Docker@2
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DH'
        repository: 'nginx'
        command: 'push'
        imageName: 'ngx/ado'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- stage: Run
  displayName: Run image 
  jobs:  
  - job: DockerContainer_Run
    displayName: Run container
    steps:
     - task: Docker@1
       displayName: DockerHub login
       inputs:
         containerregistrytype: 'Container Registry'
         dockerRegistryEndpoint: 'DH'
         command: login
     - script: docker run -d -p 8080:80 -p 8443:443 --name ngnx ngx/ado
       displayName: 'Run a docker conatiner'
